[package]
name = "bv2av"
version = "0.1.0"
authors = ["Weihao Qu <tjjzqwh@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"

[profile.release]
lto = true
